var _tmr=_tmr||[];
(function(){function Fb(a){!ia&&"number"===typeof a&&(ia=a);return $&&Gb&&bb?(cb=[Gb-$,bb-$,Na?Na-$:null,Oa?Oa-$:null,ia?ia-$:null].join("/"),Na&&(Oa&&ia)&&(Fb=function(){return cb}),cb):null}function n(a,b,c){a.addEventListener?a.addEventListener(b,c,!1):a.attachEvent&&a.attachEvent("on"+b,c)}function M(a,b,c){a.removeEventListener?a.removeEventListener(b,c,!1):a.detachEvent&&a.detachEvent("on"+b,c)}function Hb(a,b){try{if(a.nodeName.toLowerCase()===b.toLowerCase())return a;if(a.parentNode)return Hb(a.parentNode,b)}catch(c){q&&
console.warn("[TopMailRu] Error#1.25",c)}return null}function Ib(a,b){if(null===a.offsetParent||(0==a.offsetHeight||0==a.offsetWidth||0==a.clientHeight||0==a.clientWidth)||b&&(0==a.offsetLeft||0==a.offsetTop))return!1;if(void 0!==f.getComputedStyle){var c=f.getComputedStyle(a,null);return"none"!==c.display&&"hidden"!==c.visibility}return!0}function aa(a,b){for(var c=0,d=b.length;c<d;c++)if(b[c]==a)return!0;return!1}function O(a){var b=typeof a;return!("number"===b||"boolean"===b||"string"===b||a.nodeType||
a===a.window)}function ba(a){return"[object Array]"===Object.prototype.toString.call(a)}function ca(){var a=arguments,b=a[0]||{},c=!1,d=1,g=a.length,h,e,k,r,u;"boolean"===typeof b&&(c=b,b=a[d++]||{});for(O(b)||(b={});d<g;d++)if(null!=(h=a[d]))for(e in h)k=b[e],r=h[e],b!==r&&(c&&r&&(O(r)||(u=ba(r)))?(u?(u=!1,k=k&&ba(k)?k:[]):k=k&&O(k)?k:{},b[e]=ca(c,k,r)):void 0!==r&&(b[e]=r));return b}function Jb(a,b,c){if(!a)return null;var d=a.match(b),g=2<arguments.length?c:0;return d&&d.length>g?d[g]:null}function Kb(a){return(""+
a).replace(/[\/\^\$\*\+\?\.\|\(\)\[\]\{\}\\]/g,"\\$&")}function db(a){return Jb(a.host,/^(?:w{3}.)?(.*)$/,1)||""}function rc(a,b,c){a=db(a);b=(b&&0<b?b:URL_HELPER__MASK_LEVEL)-1;var d=1;a=a.replace(RegExp("^.*(?:\\.((?:[^\\.]+\\.){"+b+"}[^\\.]+$))"),"$1");if(d=a.match(/\./g))d=d.length;a="(?:^|\\.{"+(b-d+1)+"})"+Kb(a)+"$";return RegExp(c?"^((?!"+a+").)*$":a)}function eb(a){var b;if(ba(a)){b=[];for(var c=0,d=a.length;c<d;c++)b.push(eb(a[c]));return b}b=a instanceof RegExp?a:RegExp("^"+Kb(a)+"$");return b.test(db(G))?
null:b}function Lb(a){var b="";try{var c=new Uint8Array(a);f.crypto.getRandomValues(c);for(var d=0;d<a;d++)b+=(c[d]%16).toString(16)}catch(g){b="";for(d=0;d<a;d++)c=Math.floor(16*Math.random()),b+=c.toString(16)}return b}function w(){return(new Date).getTime()}function D(a,b){var c={data:b,raw:a,url:fb(a)},d;if(!sc||"function"!==typeof navigator.sendBeacon)d=!1;else{c.dataSplitter=";";var g=gb(c.data,c.dataSplitter);try{d=!0===navigator.sendBeacon(c.url,g)}catch(h){d=!1}}d||(void 0===b?(c.dataSplitter=
";",c.open=tc,c.connect=uc,c.startListen=vc,c.stopListen=wc,c.open(c),c.connect(c)):("function"===typeof f.XMLHttpRequest?(c.dataSplitter=";",c.open=xc,c.connect=yc,c.startListen=zc,c.stopListen=Ac,c.open(c),c.connect(c),d=!0):d=!1,d||Bc(c)))}function Bc(a){var b=l.createElement("iframe"),c=l.createElement("div");c.setAttribute("style","position: absolute !important; top: -9999px !important; left: -9999px !important; width: 1px !important; height: 1px !important;");c.appendChild(b);l.body.appendChild(c);
try{var d=b.contentWindow.document,g=d.createElement("div"),h;for(h in a.data)if(a.data.hasOwnProperty(h)){var e=a.data[h],k=typeof e;if("string"===k||"number"===k){var r=d.createElement("input");r.setAttribute("type","hidden");r.setAttribute("name",h);r.value=e;g.appendChild(r)}}var u=d.createElement("form");u.setAttribute("action",a.url);u.setAttribute("method",Mb);u.setAttribute("enctype",Nb);u.appendChild(g);var f=d.createElement("div");f.appendChild(u);d.body.appendChild(f);var m=function(){try{M(b,
"load",m),l.body.removeChild(c)}catch(a){q&&console.warn("[TopMailRu] Error#1.2",a)}};n(b,"load",m);u.submit()}catch(s){q&&console.warn("[TopMailRu] Error#1.3",s)}}function xc(a){a._connection=new f.XMLHttpRequest}function yc(a){a._connection.open(Mb,a.url);a._connection.setRequestHeader("Content-Type",Nb);a._connection.send(gb(a.data,a.dataSplitter))}function zc(a){n(a._connection,"load",a._onload);n(a._connection,"error",a._onerror)}function Ac(a){M(a._connection,"load",a._onload);M(a._connection,
"error",a._onerror)}function tc(a){a._connection=new Image}function uc(a){a._connection.src=a.url+gb(a.data,a.dataSplitter)}function vc(a){a._connection.onload=a._onload;a._connection.onerror=a._onerror}function wc(a){a._connection.onload=null;a._connection.onerror=null}function gb(a,b){var c=b||";",d="",g;for(g in a)if(a.hasOwnProperty(g)){var h=a[g],e=typeof h;if("string"===e||"number"===e)d+=c+escape(g)+"="+escape(h)}return d}function fb(a){a="string"===typeof a?a:"/";return"https://top-fwz1.mail.ru"+
("/"===a.substring(0,1)?"":"/")+a}function P(a){return(a=l.cookie.match(RegExp("(?:^|; )"+a.replace(/([\.$?*|{}\(\)\[\]\\\/\+^])/g,"\\$1")+"=([^;]*)")))?decodeURIComponent(a[1]):null}function ja(a,b,c){c=c||{};var d=c.expires;"number"===typeof c.expires&&(d=new Date,d.setTime(d.getTime()+c.expires));d&&d.toUTCString&&(d=d.toUTCString());c.expires=d;a=a+"="+encodeURIComponent(b);for(var g in c)if((b=c[g])||0===b)a+="; "+g,!0!==b&&(a+="="+b);l.cookie=a}function hb(a,b){var c=b||{};c.expires=-1;ja(a,
"",c)}function Cc(){var a="tmr"+(""+Math.random()).slice(2);try{return U=f.localStorage||null,U.setItem(a,a),U.removeItem(a),!0}catch(b){return U=null,q&&console.warn("[TopMailRu] Error#1.4",b),!1}}function za(a){try{return U.getItem(a)}catch(b){q&&console.warn("[TopMailRu] Error#1.5",b)}return null}function Aa(a,b){try{U.setItem(a,b)}catch(c){q&&console.warn("[TopMailRu] Error#1.6",c)}}function Dc(){if(!V)return null;for(var a=G.hostname.split(".").reverse(),b,c=1,d=a.length;c<d;c++){b=a[0];for(var g=
1;g<=c;g++)b=a[g]+"."+b;var g=""+w(),h={domain:b,path:"/",expires:3E5};try{ja("tmr_tcdhn",g,h);var e=P("tmr_tcdhn");hb("tmr_tcdhn",h);if(e===g)return b}catch(k){q&&console.warn("[TopMailRu] Error#1.8",k)}}return null}function Ob(a,b){V&&ja(a,b,ib);ka&&Aa(a,b)}function jb(a,b,c){var d=l.createElement("script");d.type="text/javascript";d.async=!0;b&&(d.onload=b);c&&(d.onerror=c);d.src=a;document.body.appendChild(d)}function Pb(a){var b=";e="+escape("detect");D(J(a,K,!1,!1)+b)}function Qb(a,b){if(a.length&&
null!==b.ecom_data){var c=xa(b.ecom_data),c=c?(""+c).substring(1,c.length-1):"";if(!(4096<c.length||-1===c.search(/\S/))){var d=kb("_m",b.ecom_method),g=kb("_t",b.ecom_type),h=kb("_jst",Rb()),c="{"+c+d+g+h+"}";D(J({id:a[0]},Ec,!1,!0)+(";ids="+escape(a.join()))+(";e="+escape(c)))}}}function kb(a,b){var c=',"'+a+'":';if(!b||!b.length)return c+"[]";try{return c+'["'+b.join('","')+'"]'}catch(d){}return c+"false"}function Fc(){var a=P(Sb);if(null===a)return null;a=a.split("|");if(3!==a.length)return null;
var b=a[2],b=w()-b;return 0>b||b>Tb?null:{id:a[0],version:a[1]}}function Ub(a){lb=!0;a.length&&jb(fb("/js/dyn-goal-config.js?ids="+a.join(",")))}function m(){}function ta(a){a&&"object"===typeof a&&(!da&&"id"in a)&&(da=a.id)}function ua(a){return!Pa?void 0:Pa[a]}function Gc(a){return(a=ua(a))&&Qa?a-Qa:void 0}function Vb(){if(Pa){for(var a=0,b="domInteractive domContentLoadedEventStart domContentLoadedEventEnd domComplete loadEventStart loadEventEnd".split(" "),c=0;c<b.length;c++){var d=ua(b[c]);if(0<
d&&(d<a||0==a))a=d}return a?a:void 0}}function W(a,b){var c=1<arguments.length?b:da;return a&&"object"===typeof a&&("id"in a&&a.id||c)}function Wb(a,b,c,d){var g=parseInt(a,10);return isNaN(g)||""+g!==""+a||g<b||g>c?d||0===d?d:null:g}function Xb(a,b){if("URL"in window){var c=b;try{c=new URL(a)}catch(d){return b}return c?a:b}return a||b}function J(a,b,c,d){ka&&Aa(va,++Q);var g="id"in a?a.id:da,h=Xb(a.url,G.href),e=Xb(a.referrer,l.referrer),k="title"in a?a.title:l.title,r;r=mb;null===r&&(r=Hc());r=
null!==r?r?1:0:null;var u="userid"in a?a.userid:R||0===R?R:void 0,m=X?X:void 0,n;n=la&&a.bfCache;var s="pageView"===a.type&&a.timespent,p=[];da&&g!==da&&p.push("sec");"dataLayer"in f&&p.push("dl");E&&p.push(["ecom"].concat(E).join("-"));var Ba=Ic();Ba&&Ba.length&&p.push(["jst"].concat(Ba).join("-"));n&&p.push("bfc");S&&s&&p.push("ts");f.top!==f&&p.push("frame");(!0===B.webdriver||l.$cdc_asdjflasutopfhvcZLmcfl_)&&p.push("wda");n=p.join(",");s=(new Date).getTimezoneOffset();p="";if(f.Intl)try{p=f.Intl.DateTimeFormat().resolvedOptions().timeZone||
""}catch(Jc){q&&console.warn("[TopMailRu] Error#1.1",Jc)}Ba=s+"/"+p;s=Yb;s=null!==s?s:Fc();p=Fb(a.start);b=b+"?_="+Math.random()+(g?";id="+escape(g):"")+(h?";u="+escape(h):"")+(e?";r="+escape(e):"");g=Wb(a.gender,1,2);b+=null!==g?";gender="+g:"";g=Wb(a.age,1,127);d=b+(null!==g?";age="+g:"")+("pid"in a?";pid="+escape(a.pid):"")+(void 0!==u?";userid="+escape(u):"")+(void 0!==m?";uparams="+escape(xa(m)):"")+(d&&k?";title="+encodeURIComponent(k):"");k=";s="+Kc+";vp=";m=u=0;l.documentElement&&(l.documentElement.clientWidth||
l.documentElement.clientHeight)?(u=l.documentElement.clientWidth,m=l.documentElement.clientHeight):"number"==typeof f.innerWidth&&(u=f.innerWidth,m=f.innerHeight);d=d+(k+(""+u+"*"+m)+";touch="+Lc+";hds="+Mc)+";sid="+nb+";ver="+Nc+";tz="+encodeURIComponent(Ba)+";st="+Vb();if(c){if(!Pa||!ob)c="";else{c=[];c.push(ob.type);c.push(ob.redirectCount);c.push(Qa);for(k=0;k<Zb.length;k++)c.push(Gc(Zb[k]));c=c.join("/")}c=";nt="+c}else c="";c=d+c+(p?";ct="+p:"")+(Ra?";gl="+Ra:"")+("device"in a?";device="+escape(a.device):
"")+";ni=";if(!B||!B.connection)p="";else{p=B.connection;d=[];for(u=0;u<$b.length;u++){k=p[$b[u]];if(void 0!==k)switch(k){case !0:k=1;break;case !1:k=0;break;default:k=(""+k).replace(/\//g,"_")}d.push(k)}p=d.join("/")}return c+p+("params"in a?";params="+escape(xa(a.params)):"")+(null!==r?";detect="+r:"")+(V||ka?";lvid="+escape([Ca,w(),Q,ma].join(":")):"")+(n?";opts="+escape(n):"")+(s?";flocid="+escape(s.id)+";flocv="+escape(s.version):"")+(ac&&Da?";fpid="+Da:"")+("version"in a?";appver="+escape(a.version):
"")+(na.support?";visible="+na.getValue():"")+";js=13"}function pb(a){a=";e="+escape(a);for(var b=0;b<F.length;b++)D(J(F[b],K,!1,!0)+a)}function Oc(){mb=!0;bc(1);if(!qb&&!Ea){Ea=!0;for(var a=0;a<F.length;a++)Pb(F[a])}}function Pc(){bc(0);mb=!1}function Hc(){var a=P(cc);if(null===a)return null;a=a.split("|");if(2!==a.length)return null;var b=a[1],b=w()-b;if(0>b||b>dc)return null;a=parseInt(a[0],10);return isNaN(a)?null:a}function bc(a){var b=w();a=[a,b].join("|");ja(cc,a,{path:"/",expires:dc})}function Qc(){var a=
0;Sa&&(a=w()-Sa);Rc||(x.dcl3=setTimeout(function(){pb("DCL/3")},Math.max(3E3-a,0)))}function Sc(){var a=0;Ta&&(a=w()-Ta);Tc||(x.pvt2=setTimeout(function(){pb("PVT/2")},Math.max(2E3-a,0)));Uc||(x.pvt15=setTimeout(function(){pb("PVT/15")},Math.max(15E3-a,0)))}function ec(){rb||setInterval(function(){_tmr.beat()},6E4)}function Vc(a,b,c,d){if(!b||!d||d===sb&&b===sb&&c===sb)return null;b={goal:Wc+b,value:c||0,params:{product_id:d}};a&&(b.id=a);return b}function Ua(){Sa=w();l.addEventListener?(M(l,"DOMContentLoaded",
Ua),_tmr.onready()):l.attachEvent&&"complete"===l.readyState&&(M(l,"readystatechange",Ua),_tmr.onready());fc()}function tb(a){Ta=w();if(la){if(a.persisted){Fa=Ga=Va=0;ub=vb=!1;S&&y.launch();a=wb;wb=[];for(var b=0,c=a.length;b<c;b++)_tmr.callbackOnReady(a[b]);a=Wa;Wa={};for(b in a)_tmr.pageView(a[b]);ec()}}else M(f,"load",tb);_tmr.onready();_tmr.onload()}function Ha(){la||(M(f,"unload",Ha),M(f,"beforeunload",Ha));_tmr.unload()}function fc(){S&&y.launch();if(Xc&&gc){window.addEventListener("message",
function(a){var c=null;try{if(c=a.data,O(c)||(c=Xa(c)),"LOAD_BUTTONS_SCRIPT"===c.type){var d;var g=document.referrer;a=null;var h=(""+c.lang).toLowerCase(),e;b:{for(var c=0,k=xb.length;c<k;c++)if(xb[c]===h){e=!0;break b}e=!1}e||(h=xb[0]);try{a=(new URL(g)).host}catch(r){}d=a&&Yc.test(a)?"https://"+a+"/top_constructor/buttons_"+h+".js":fb("/js/dyn-goal-wizard-"+h+".js");jb(d)}}catch(f){}});if(window.opener)try{window.opener.postMessage({type:"READY"},document.referrer)}catch(a){}lb||(Ya.push.apply(Ya,
Ia),Ub(Ia))}}if("[object Array]"===Object.prototype.toString.call(_tmr)){var Gb=(new Date).getTime(),bb=null,Na=null,Oa=null,ia=null,$=null,cb=null,K="/tracker",Ec="/datalayer",f=window,B=navigator,l=document,G=location,Y="string"===typeof G.hostname?G.hostname:"",Ja=-1!=Y.search(/(^|\.)odnoklassniki\.ru$/)||-1!=Y.search(/(^|\.)ok\.ru$/),hc=-1!=Y.search(/(^|\.)vk\.com$/);Y.search(/(^|\.)mail\.ru$/);var Zc=-1!=Y.search(/(^|\.)lamoda\.ru$/),$c=-1!=Y.search(/(^|\.)kommersant\.ru$/);Y.search(/(^|\.)top\.mail\.ru$/);
Y.search(/(^|\.)dzen\.ru$/);var ic="string"===typeof G.search&&-1!=G.search.search(/[?&]rb_clickid=/),q="string"===typeof G.search&&-1!=G.search.search(/[?&]tmr_debug=1(?:&|$)/),sc=!1,rb=Ja||hc||Zc||$c,Tc=!ic,Uc=Ja,Rc=!ic,qb=!1,S=f.performance&&"visibilityState"in l,ad=[36383],bd=!(Ja||hc),Xc=!0,ac=!0,jc=f.JSON&&f.JSON.stringify&&f.JSON.parse,la="onpageshow"in f&&"onpagehide"in f,gc="URL"in f,xa=jc?f.JSON.stringify.bind(f.JSON):function(a){return""},Xa=jc?f.JSON.parse.bind(f.JSON):function(a){return{}},
xb=["ru","en"],Yc=/^(ads\d+\.my\.com)$/,Mb="POST",Nb="application/x-www-form-urlencoded",V=!(0===G.hostname.search(/^(\d+.)+\d+$/g)||-1!==G.hostname.search(/:/g)),U=null,ka=Cc(),ib={domain:Dc(),path:"/",expires:287712E5};(function(){var a;if(a=l.cookie.match(RegExp("(?:^|; )(tmr_tcdhn\\d+)=([^;]*)","g"))){for(var b=[],c,d=0,g=a.length;d<g;d++)c=a[d],(c=c.match(/(?:^|; )(tmr_tcdhn\d+)=([^;]*)/))&&b.push(c.slice(1));a=b}else a=null;if(a){d=0;for(g=a.length;d<g;d++)b=a[d][0],hb(b,ib)}})();var Ea=!1,
mb=null,dc=864E5,cc="tmr_detect",cd=function(){function a(a,b){for(var c=a.length,e,k,f=0;f<b;f++)k=Math.floor(Math.random()*c),e=a[f],a[f]=a[k],a[k]=e;return a.slice(0,b)}function b(b,g){var h=l.createElement("div"),e=String.fromCharCode(97,100,118,98,108,111,99,107,32,97,100,118,101,114,116,98,108,111,99,107,32,97,100,118,101,114,116,66,108,111,99,107,32,98,45,114,98,32,98,97,110,110,101,114,95,50,52,48,32,112,45,116,97,114,103,101,116,32,112,117,98,95,51,48,48,120,50,53,48,32,112,117,98,95,51,
48,48,120,50,53,48,109,32,112,117,98,95,55,50,56,120,57,48,32,114,98,95,98,111,100,121,32,114,98,45,102,108,111,97,116,105,110,103,32,114,98,45,115,108,111,116,32,114,98,45,118,105,100,101,111,45,119,105,100,103,101,116,32,116,101,120,116,45,97,100,32,116,101,120,116,45,97,100,45,108,105,110,107,115,32,116,101,120,116,45,97,100,115,32,116,101,120,116,45,98,97,110,110,101,114,32,116,101,120,116,95,97,100,32,116,101,120,116,95,97,100,115,32,116,101,120,116,65,100,32,116,101,120,116,97,100,32,116,101,
120,116,65,100,115,32,116,101,120,116,97,100,115,32,116,103,98,45,98,97,110,110,101,114,32,116,114,103,45,98,45,98,97,110,110,101,114,45,98,108,111,99,107).split(" "),e=a(e,c);h.setAttribute("class",e.join(" "));h.setAttribute("style","position: absolute !important; top: -9999px !important; left: -9999px !important; width: 1px !important; height: 1px !important;");h.setAttribute("id","trg-b-banners-1");h.setAttribute("data-view","SlotView.mimic");this.bait=l.body.appendChild(h);this.bait.offsetParent;
this.bait.offsetHeight;this.bait.offsetLeft;this.bait.offsetTop;this.bait.offsetWidth;this.bait.clientHeight;this.bait.clientWidth;this.loopNumber=0;this.fnPositive=b||null;this.fnNegative=g||null;var k=this;setTimeout(function(){k._checkBait.call(k)},1)}var c=7;b.prototype._checkBait=function(){if(Ea)this._stop();else{var a=null!==l.body.getAttribute("abp")||!Ib(this.bait,!0);(!0===a||10<=++this.loopNumber)&&this._stop();var b;if(a&&this.fnPositive)try{b=this.fnPositive,b()}catch(c){q&&console.warn("[TopMailRu] Error#1.9",
c)}else if(!a&&10>this.loopNumber){var e=this;setTimeout(function(){e._checkBait.call(e)},50*this.loopNumber)}else try{b=this.fnNegative,b()}catch(k){q&&console.warn("[TopMailRu] Error#1.10",k)}}};b.prototype._stop=function(){try{l.body.removeChild(this.bait)}catch(a){q&&console.warn("[TopMailRu] Error#1.11",a)}};return function(a,c){new b(a,c)}}(),E=null,kc="ecommerce",C="dataLayer",ea=null,yb=!1,Za=[],dd=[36383,2540645,3171181,3074137,2057653],ed=[],zb;(function(){function a(a,b){for(var c=0,d=
b.length;c<d;c++)-1===a.indexOf(b[c])&&a.push(b[c])}function b(b,c,d){for(var g={ecom_method:[],ecom_type:[],ecom_data:{events:[]}},h=0,k=b.length;h<k;h++){var e=n[b[h]];if(e){a(g.ecom_method,[b[h]]);for(var f=0,u=e.length;f<u;f++)for(var r=0,l=d.length;r<l;r++){var p=e[f][d[r]];if(p)for(var t=0,m=c.length;t<m;t++)if(-1!==e[f].type.indexOf(c[t])){a(g.ecom_type,[c[t]]);a(g.ecom_data.events,p);break}}}}return g}function c(a,b,c){if(!a||!c||!(b in n))return null;for(var d,g=0,h=n[b].length;g<h;g++)if(d=
n[b][g],c in d&&-1!==d[c].indexOf(a))return{ecom_method:[b],ecom_type:d.type.slice(),ecom_data:{}};return null}function d(a){for(var d=[],e,f,l=0,fd=a.length;l<fd;l++)if(f=a[l]){e=null;try{if(f.ecommerce)e=g(f)||h(f);else if(null===f.ecommerce)e=null;else if(f.event){var m={event:f.event,ecommerce:{}};e=g(m)||h(m)}else if("event"===f[0]){var oa=f[1],n=f[2],z=c(oa,r,s);z&&(z.ecom_data[oa]=n);e=z}else if(f.event===kc)a:{for(var Ka=b([k],[u],[p]),Ab=0,t=Ka.ecom_data.events.length;Ab<t;Ab++)if(!f.hasOwnProperty(Ka.ecom_data.events[Ab])){e=
null;break a}delete Ka.ecom_data.events;Ka.ecom_data[kc]=f;e=Ka}}catch(w){q&&console.warn("[TopMailRu] Error#1.23",w),e=null}e&&(d.push(e),Za.push(e))}if(d.length){a=0;for(e=d.length;a<e;a++)Qb($a,d[a]);E||(E=[0,0,C]);E[0]+=d.length;e=a=0;for(l=d.length;e<l;e++)a+=xa(d[e].ecom_data).length;E[1]+=a}}function g(a){var b,d;for(d in a.ecommerce)if(a.ecommerce.hasOwnProperty(d)&&(b=c(d,k,l))){if(a.event&&(d=c(a.event,k,m)))for(var g=0,e=b.ecom_type.length;g<e;g++)-1===d.ecom_type.indexOf(b.ecom_type[g])&&
(b.ecom_type.splice(g,1),e--,g--);b.ecom_data=a.ecommerce;return b}return null}function h(a){var b=a.event,d=c(b,k,m);d&&(d.ecom_data[b]=a.ecommerce);return d}function e(a){if((a=f[a])&&"function"===typeof a.push)d(a),ea=a.push,a.push=function(){var a=ea.apply(this,arguments);d([].slice.call(arguments,0));return a}}var k="push",r="gtag",u="gse",l="inner",m="outer",s="external",p="required",n={};n[r]=[{type:["gee"],external:"add checkout checkout_option checkout_progress click detail promo_click remove select_content set_checkout_option view_refund".split(" ")},
{type:["ga4"],external:"earn_virtual_currency join_group level_end level_start level_up post_score select_content spend_virtual_currency tutorial_begin tutorial_complete unlock_achievement ad_impression login search share sign_up add_payment_info add_shipping_info add_to_wishlist generate_lead select_item select_promotion view_cart view_item_list".split(" ")},{type:["gee","ga4"],external:"add_to_cart begin_checkout purchase refund remove_from_cart view_item view_promotion".split(" ")}];n[k]=[{type:[u],
required:["transactionId","transactionTotal"]},{type:["ga4"],outer:b([r],["ga4"],[s]).ecom_data.events},{type:["gee"],inner:"click checkout checkout_option impressions promoClick promoView refund".split(" "),outer:"addToCart checkout checkoutOption productClick productDetail ProductImpressions promotionClick promotionView removeFromCart transactionPush".split(" ")},{type:["ym","gee"],inner:["add","detail","purchase","remove"]},{type:["mt"],outer:["mt_order","mt_refund"]}];zb=function(a){if(!(a===
C&&ea)){a!==C&&(Za=[]);var b=f[C];b&&"function"===typeof b.push&&ea&&(b.push=ea,ea=null);e(a);yb=!0}}})();var Rb=function(){var a=[{id:"gtag",globalVars:["google_tag_manager"]},{id:"ga",globalVars:["GoogleAnalyticsObject"]},{id:"ym",globalVars:["Ya",{re:"yaCounter\\d+"}]},{id:"vk",globalVars:["VK"]},{id:"vk",globalVars:["vkAsyncInit"]}],b={};return function(){var c;try{c=Object.keys(f).join(",")}catch(d){c=null}for(var g=[],h,e=0,k=a.length;e<k;e++){h=b[a[e].id];if(void 0===h)a:{h=a[e].globalVars;
for(var r=c,u=0,l=h.length;u<l;u++){var m=h[u];if("string"===typeof m&&!(m in f)||"string"===typeof m.re&&(r&&-1===r.search(RegExp("($|,)"+m.re+"(,|^)","m"))||1===l)){h=!1;break a}}h=!0}h&&(b[a[e].id]=!0,aa(a[e].id,g)||g.push(a[e].id))}return g}}(),Ic=Rb,Tb=864E5,Sb="tmr_floc",Yb=null;(function(a){try{l.interestCohort&&"function"===typeof l.interestCohort&&l.interestCohort().then(function(a){Yb={id:a.id,version:a.version};a=[a.id,a.version];var b=w();a=a.concat(b).join("|");ja(Sb,a,{path:"/",expires:Tb})},
function(){})}catch(b){}})();var Bb=!1,Ra=null,La=null,Cb=!1,lc;(function(){function a(a){try{var c=a.state;La=c in e?e[c]:h;Cb=c===g;Bb&&b(Cb)}catch(d){}}function b(a){try{a?(B[d].getCurrentPosition(c),f||(f=B[d].watchPosition(c))):(f&&B[d].clearWatch(f),c(null))}catch(b){}}function c(a){if(a)try{var b=a.coords,b=[b.latitude,b.longitude,b.accuracy,b.altitude,b.altitudeAccuracy,b.heading,b.speed];a=0;for(var c=b.length;a<c;a++)"number"!==typeof b[a]&&(b[a]="");b.splice(0,0,La);Ra=b.join("/")}catch(d){}else Ra=
La}var d="geolocation",g="granted",h="u",e={denied:"d"};e[g]="g";e.prompt="p";var f=null;(function(){La=h;c(null);try{d in B?B.permissions&&B.permissions.query({name:d}).then(function(b){a(b);b.onchange=function(){a(b)}}):La="n"}catch(b){}})();lc=b})();var na={support:!1},na=function(){function a(){g(e)}function b(){g(e,s)}function c(a){a.persisted&&(p[e]=null,p[k]=null,g(e,q))}function d(){return r?!l[r]:null}function g(a,b){var c=w(),g="undefined"===typeof b?d():b;if(null===p[a])p[a]={ts:c,state:g,
total:0};else{var e=p[a];if(e.state!==g&&!(e.state===s&&g!==q)){var f=c-e.ts,k=e.state;e.ts=c;e.state=g;f<h||(k===q?(e.total+=f,y&&y(c,f)):k===x&&v&&v(c,f))}}}var h=5,e="auto",k="user",r=null,m=null,q=!0,x=!1,s=null;"hidden"in l?(r="hidden",m="visibilitychange"):"mozHidden"in l?(r="mozHidden",m="mozvisibilitychange"):"webkitHidden"in l?(r="webkitHidden",m="webkitvisibilitychange"):"msHidden"in l&&(r="msHidden",m="msvisibilitychange");var p={};p[e]=null;var y=p[k]=null,v=null;return{support:!!r,auto:function(d,
g){y=d||null;v=g||null;r&&(a(),n(l,m,a));la?(n(f,"pageshow",c),n(f,"pagehide",b)):(n(f,"beforeunload",b),n(f,"unload",b))},set:function(a){g(k,!!a)},getLog:function(){var a=w(),b={},c,d;for(d in p)c=p[d],b[d]=c?c.total:0,c&&c.state&&(b[d]+=a-c.ts);return b},getValue:d}}();na.auto();var mc={enabled:!1};if(gc){var nc=function(){var a="checkbox color date datetime-local email file month number password radio range search tel text time url week".split(" ");return{analyze:function(b){if(!b)return null;
for(var c=[].slice.apply(b.elements),d=[],g=[],f=0,e=c.length;f<e;f++){var k;a:switch(k=c[f],k.tagName.toLowerCase()){case "button":k=!1;break a;case "input":var l=k.type.toLowerCase();if(l&&-1===a.indexOf(l)){k=!1;break a}default:k=Ib(k,!1)&&k.name&&!1===k.disabled}k&&(d.push(c[f].name),g.push(c[f].type))}return{node:b,inputsName:d.length?d:null,inputsType:g.length?g:null}},getFormByInput:function(a){if(!a)return null;a=a.form||a.getAttribute("form");return"string"===typeof a?document.getElementById(a)||
null:a instanceof HTMLElement?a:null}}}(),mc=function(){function a(a){a=a||f.event;var c=(a.which||a.keyCode)===M;if("which"in a&&a.which===F||"button"in a&&a.button&F||c){a:{a=a.target||a.srcElement;for(var c=0,d=e.length;c<d;c++){var l;b:{l=a;for(var z=e[c],p=0,n=z.types.length;p<n;p++){var t;c:{var s=l;t=z.types[p];var A=null;if(t.filter.tagName)for(var L=0,v=t.filter.tagName.length;L<v&&!(A=Hb(s,t.filter.tagName[L]));L++);else A=s;if(A){if(t.filter.attr)for(s in s=void 0,t.filter.attr)if(t.filter.attr.hasOwnProperty(s)&&
(L=t.filter.attr[s],v=A[s],!0===L&&!v||!1===L&&v||ba(L)&&-1===L.indexOf(v))){t=null;break c}t={source:A,type:t.type,detail:A.tagName}}else t=null}if(t){t.category=z.category;l=t;break b}}l=null}if(l){a=l;break a}}a=null}if(a){if(a.category===g){try{a.data=new URL(a.source.href)}catch(D){}if(!a.data)return}else if(a.category===h){if(a.data=nc.analyze(nc.getFormByInput(a.source)),!a.data)return}else return;c=J;if(c.enabled&&c.modes){d=0;for(l=c.modes.length;d<l;d++)if(z=a,p=c.modes[d],z.category===
p.mode)if(z.category===g||z.category===h){if(p=p.categories,z.data){n=void 0;c:{n=0;for(t=p.length;n<t;n++){for(var A=z,s=p[n],L={category:z.category},v=[],T=0,G=s.types.length;T<G;T++){var qa=s.types[T],K=ca({type:s.category},L),E=y in qa,B;w in qa?B=b(A,qa,K,w):E&&(B=ca({source:A.source,data:A.data,detail:qa.type},K));if(B&&(!E||!b(A,qa,K,y)))if(v.push(B),(qa.rule&x)!==x)break}if(A=v.length?v:null){n=A;break c}}n=null}if(n){z=0;for(p=n.length;z<p;z++)c:{t=n[z];A={type:"sendEvent",category:"_"+t.category,
action:t.detail};if(t.category===g&&(t.type===k||t.type===m)){if(A.label=t.data.href,!A.label)break c}else if(t.category===u&&(A.label=t.data.node.action,!A.label))break c;_tmr.push(A)}}}}else q&&console.warn("[TopMailRu] Error#1.24","Not found tracking for type",z.type)}}}}function b(a,b,d,g){var e=!1,f=b[g];if(ba(f)){var h=b[g+"Rule"]||D;g=(h&s)===s;for(var h=(h&p)===p,k=0,l=f.length;k<l&&!(e=c(a,f[k]),g&&e);k++)if(h&&!e)return null}else e=c(a,f);return!e?null:ca({source:a.source,data:a.data,detail:b.type},
d)}function c(a,b){var c=b.rule||D,g=(c&s)===s,c=(c&p)===p,e=!1,f;for(f in b)if(b.hasOwnProperty(f)&&"rule"!==f){var e=b[f],h;switch(f){case "domain":h=db(a.data);break;case "fileExtension":h=Jb(a.data.pathname,/.\.([^\.]+)$/,1)||"";break;default:h=a.data[f]}e=!0===e?!!(ba(h)?h.length:h):!1===e?!(ba(h)?h.length:h):d(h,e);if(g&&e)break;else if(c&&!e)return!1}return e}function d(a,b){var c=a;if(c)if(ba(c)){if(!c.length)return!1}else c=[c];else return!1;var d=b,e=D;if(O(d)&&!ba(d)){if(!ba(d.value))return!1;
e=d.rule||e;d=d.value}a:{for(var g=(e&v)===v,f=(e&s)===s,e=(e&p)===p,h=!1,k=0,l=d.length;k<l;k++){var m=d[k];if(m){var n="string"===typeof m;n&&!g&&(m=m.toLowerCase());var r=m instanceof RegExp;if(n||r){var h=!0,q;b:{q=c;for(var u=g,w=0,y=q.length;w<y;w++){var x=u?q[w]:q[w].toLowerCase();if(r&&m.test(x)||n&&m===x){q=!0;break b}}q=!1}if(f&&q){c=!0;break a}else if(e&&!q){c=!1;break a}}}}c=f?!1:e?h?!0:!1:void 0}return c}var g="click",h="submit",e=[{category:h,types:[{type:"button",filter:{tagName:["input",
"button"],attr:{type:["submit","image"]}}}]},{category:g,types:[{type:"a",filter:{tagName:["a"],attr:{href:!0}}}]}],k="file",m="resource",u="submit",w="filter",y="stop",s=1,p=2,v=4,x=8,D=s,J={enabled:!0,modes:[{mode:h,categories:[{category:u,types:[{type:"lead",filter:[{inputsName:["phone"],inputsType:["tel"],rule:s},{inputsName:["email"],inputsType:["email"],rule:s}],filterRule:p,stop:{inputsName:{value:["password"]}}},{type:"form",filter:{inputsName:!0}}]}]},{mode:g,categories:[{category:"contact",
types:[{type:"email",filter:{protocol:["mailto:"]}},{type:"phone",filter:{protocol:["tel:"]}}]},{category:k,types:[{type:"file",filter:{fileExtension:"7z bz2 gz apk iso cab dmg msi rar tar zip exe txt doc docx ppt pptx xls xlsx csv pdf psd rtf ods djvu eps 3gp aac ac3 avi flac flv divx midi mka mkv mp3 mp4 mpeg mpg mov ogg vob wav webm wma wmf wmv torrent".split(" ")}}]},{category:m,types:[{type:"outgoing",rule:x,stop:{domain:[rc(G.host,3,!1)],href:[/password/]}},{type:"messenger",filter:{domain:eb("vk.me t.me telegram.me telegram.im web.telegram.org m.me web.whatsapp.com api.whatsapp.com chat.whatsapp.com wa.me".split(" "))},
stop:{href:[/password/]}},{type:"social",filter:{domain:eb("vk.com vkontakte.ru m.vk.com vk.ru ok.ru m.ok.ru odnoklassniki.ru facebook.com m.facebook.com fb.com twitter.com linkedin.com instagram.com tiktok.com youtube.com youtu.be m.youtube.com".split(" "))},stop:{href:[/password/]}}]}]}]},F=1,M=13;return{enabled:!0,start:function(){n(l,"click",a);n(l,"keypress",a)}}}();bd&&mc.start()}var y=function(){function a(){b(null)}function b(a){g();a?(V=a===T,pa=a):pa=X&&null!==V?V?T:ca:l.visibilityState;
a=C();for(var b in fa)y(b,a)}function c(){if(!1!==P){M(f,A,ja);ja=null;f.clearInterval(ma);na=ma=null;M(l,L,ea);ea=null;X&&(M(f,Y,ha),M(f,$,ia),ia=ha=null);h(!0);for(var a in Z){var b=a,c=Z[b];c&&(c=c.key,O(b),oa(),delete Z[b],z(null,c))}H=null;ga=[];wa=[];I={};Z={};fa={};P=!1}}function d(a,b,c){var d=a+"_"+b;if(d in I)return!1;var e=w(),g=C(),f=E(d,e,nb);b=I[d]={id:a||null,name:b,key:f,canUseInBackground:!!c,startTS:e,updateTS:g,timespent:{}};if(a)if(wa.push(d),d=b.canUseInBackground,b=fa[a]){if(c=
b.isActive,!c&&(e=H&&aa(a,H)))if(c=pa===T||d)b.updateTS=g,b.isActive=!0}else e=H&&aa(a,H),c=pa===T||d,fa[a]={isActive:e&&c,updateTS:g,timespent:{}};else ga.push(d);return!0}function g(a,b){var c,d;2>arguments.length?(c=wa.concat(ga),d=R):(c=[a+"_"+b],d=W);e(c,d)}function h(a,b,c){var d=!1,g=[],f=[];2>arguments.length?(g=wa.slice(),(d=!!arguments[0])&&(g=g.concat(ga))):(d=a+"_"+b,-1!==wa.indexOf(d)?g=[d]:-1!==ga.indexOf(d)&&(c?g=[d]:f=[d]));e(g,da);e(f,W)}function e(a,b){var c=C(),d=[],e,g,f;e=0;for(g=
a.length;e<g;e++)f=a[e],-1!==wa.indexOf(f)?k(f,b,c):-1!==ga.indexOf(f)&&d.push(f);e=0;for(g=d.length;e<g;e++)f=d[e],k(f,b,c);if(b===R&&(U=c,U-P>=sa)){for(var h in I)q(h);for(h in Z)if(c=h,d=Z[c])O(c),z(c,d.key);P=U}}function k(a,b,c){var d=I[a];if(d&&!1!==d.updateTS)if(d.timespent[pa]=(d.timespent[pa]||0)+(c-(d.updateTS||U)),-1!==ga.indexOf(a)&&B(null,c),b===da)d.updateTS=!1,q(a);else if(b===t){d.updateTS=c;var e;a:{if(b=I[a])for(e in b.timespent)if(b.timespent[e]>ra){e=!1;break a}e=!0}e?(m(a),oa()):
q(a)}else d.updateTS=b===R?null:c,m(a),oa()}function m(a,b,c){var d=I[a];if(!d)return null;var e=b||d.key;b=N[e];N[e]={uid:a,name:d.name,counterID:c||d.id||H,canUseInBackground:d.canUseInBackground,isActive:!1!==d.updateTS,startTime:d.startTS,timespent:{}};a=N[e].timespent;var d=d.timespent,g;for(g in d)a[g]=d[g];if(c&&(c=fa[c]))if(e=N[e]){e.common={};e=e.common;c=c.timespent;for(var f in c)e[f]=c[f]}return b||null}function q(a){var b=I[a];b&&(m(a),v(a,b.key))}function v(a,b){var c=N[b];if(c)if(ba(c.counterID)){var d=
N[b];if(d){var c=d.counterID,e=[],g,f,h,k;if(c){h=0;for(k=c.length;h<k;h++){f=c[h];g=E(b,f);e.push(g);f=m(a||d.uid,g,f);var l=void 0;f&&(l=N[g],Q(l.timespent,f.timespent),f.common&&(l.common=l.common||{},Q(l.common,f.common)))}}delete N[b];oa();if(a&&a in I)if(d.isActive){s(a);h=0;for(k=c.length;h<k;h++)if(d=fa[c[h]])for(var n in d.timespent)d.timespent[n]=0}else p(a);h=0;for(k=e.length;h<k;h++)x(e[h])}}else if(n=N[b])(c=a&&a in I)&&!n.isActive&&p(a),e=x(b),c&&(e&&n.isActive)&&s(a)}function x(a){var b;
if(b=N[a]){var c=S(b.timespent);if(!1===b.canUseInBackground&&b.isActive&&0===c.fg)b=null;else{c=[b.name,b.startTime,b.canUseInBackground?1:0,c.fg,c.bg];if(b.common){var d=S(b.common);(d.fg||d.bg)&&c.push(d.fg,d.bg)}b={id:b.counterID,msg:c.join("/")}}}else b=!1;if(!b)return!1;c=";e="+escape("TS:"+b.msg);D(J({id:b.id},K,!1,!1)+c);delete N[a];oa();return!0}function s(a){if(a=I[a])for(var b in a.timespent)a.timespent[b]=0}function p(a){if(a in I){var b;-1!==(b=ga.indexOf(a))&&ga.splice(b,1);if(-1!==
(b=wa.indexOf(a)))if(wa.splice(b,1),b=I[a].id){var c=fa[b];if(c){var d=c.isActive;d&&G(c,C());d=F(b,a);d||(c.isActive=!1)}}delete I[a]}}function y(a,b){var c=fa[a];if(c){var d=H&&aa(a,H),e=F(a);c.isActive=d&&e;c.updateTS=b}}function B(a,b){if(a){var c=fa[a];c&&(c.isActive?G(c,C()):c.updateTS=b)}else for(c in fa)B(c,b)}function F(a,b){for(var c in I)if(c!==b&&I[c].id===a&&(pa===T||I[c].canUseInBackground))return!0;return!1}function G(a,b){a&&(a.timespent[pa]=(a.timespent[pa]||0)+(b-a.updateTS),a.updateTS=
b)}function E(a){return[].join.call(arguments,"_")}function Q(a,b){for(var c in b)a[c]=(a[c]||0)+(b[c]||0)}function S(a){var b=a[T]||0,c=0,d;for(d in a)d!==T&&(c+=a[d]);return{fg:b,bg:c}}function C(){return Math.floor(f.performance.now())}function oa(){if(ka){var a={};a[ua]=N;a[va]=ya;Aa(ta,xa(a)||"")}}function O(a){var b=Z[a];b&&(ya[b.key]={uid:a,name:b.name,counterID:b.id,value:b.value})}function z(a,b){if(ya[b]){var c;if(c=ya[b])if(0===c.value)c=null;else{var d=[c.name,c.value].join("/");c={id:c.counterID,
msg:d}}else c=!1;c&&(d=";e="+escape("TS:"+c.msg),D(J({id:c.id},K,!1,!1)+d));!1!==c&&(delete ya[b],oa());if(c&&a&&(c=Z[a]))c.value=0}}var W=1,R=2,t=4,da=8,A=la?"pagehide":"unload",L="visibilitychange";"mozHidden"in l?L="mozvisibilitychange":"webkitHidden"in l?L="webkitvisibilitychange":"msHidden"in l&&(L="msvisibilitychange");var Y="focus",$="blur";"onfocusin"in l&&(Y="focusin",$="focusout");var T="visible",ca="hidden",qa=["0"],X=!1,ra=100,sa=12E4,P=!1,U=!1,H=null,ga=[],wa=[],I={},pa,V=null,ma,na,
ea,ha,ia,ja,ta="tmr_tslog",ua="activity",va="count",N={},Z={},ya={},fa={};return{init:function(){if(ka){var a=Xa(za(ta)||"{}");N=a[ua]||{};ya=a[va]||{}}for(var b in N)v(null,b);for(b in ya)z(null,b)},launch:function(){!1===P&&(P=C(),U=C(),pa=X&&null!==V?V?T:ca:l.visibilityState,ja=c.bind(f),n(f,A,ja),na=a.bind(f),ma=f.setInterval(na,1E4),ea=b.bind(f,null),n(l,L,ea),X&&(ha=b.bind(f,T),ia=b.bind(f,ca),n(f,Y,ha),n(f,$,ia)))},enable:function(a){if(H){if(aa(a,H))return;e(ga,t)}else{for(var b=0,c=qa.length;b<
c;b++)d(null,qa[b],!1);H=[]}H.push(a);y(a,C())},disable:function(a){if(H){var b;a:{b=0;for(var c=H.length;b<c;b++)if(H[b]==a)break a;b=-1}if(-1!==b&&(e(ga,t),H.splice(b,1),b=C(),a=fa[a]))a.isActive=!1,a.updateTS=b}},startActivity:d,updateActivity:g,stopActivity:h,incCount:function(a,b){var c=a+"_"+b,d;if(!(d=Z[c]))if(c in Z)d=Z[c];else{d=w();var e=E(b,d,nb);d=Z[c]={id:a,name:b,key:e,startTS:d,value:0}}d&&d.id===a&&(d.value++,O(c),oa())},defaultID:function(){return H?H[0]:void 0}}}(),lb=!1,Da=null;
ac&&function(){function a(){var a=za(g);if(a)try{(a=Xa(a))&&(Da=a.fpid||null)}catch(b){}c()}function b(){c()}function c(){Aa(d,xa({fpid:Da,ts:w()}))}var d="tmr_trgfpid",g="rb_sync_id";(function(){var c=ka?za(d):null;if(c)try{if(c=Xa(c))if(Da=c.fpid||null,864E5>w()-c.ts)return}catch(e){}jb("https://privacy-cs.mail.ru/static/sync-loader.js",a,b)})()}();var Nc="60.5.1",Va=0,Ga=0,nb=Lb(16),R=null,X=null,Fa=0,va="tmr_reqNum",Q=null;V&&(Q=P(va)||null,null!==Q&&hb(va,ib));ka&&null===Q&&(Q=za(va)||null);
Q=null===Q?0:parseInt(Q,10);ka&&Aa(va,Q);var ma=(V?P("tmr_lvid"):null)||(ka?za("tmr_lvid"):null),Ca=(V?P("tmr_lvidTS"):null)||(ka?za("tmr_lvidTS"):null);if(null===ma||-1===ma.search(/^[0-9a-fA-F]+$/))ma=Lb(32);Ob("tmr_lvid",ma);if(null===Ca||-1===Ca.search(/^\d+$/))Ca=""+w();Ob("tmr_lvidTS",Ca);var da=0,F=[],Ia=[],ab=[],$a=[],Ya=[],Wa={},Lc="ontouchstart"in f||1<(B.maxTouchPoints||B.msMaxTouchPoints)?"1":"0",Mc=f.devicePixelRatio||0,Kc=function(){var a=f.screen;return a?a.width+"*"+a.height:""}(),
oc=f.performance||f.mozPerformance||f.msPerformance||f.webkitPerformance||{},Pa=oc.timing||{},ob=oc.navigation||{},Zb="unloadEventStart unloadEventEnd redirectStart redirectEnd fetchStart domainLookupStart domainLookupEnd connectStart connectEnd secureConnectionStart requestStart responseStart responseEnd domLoading domInteractive domContentLoadedEventStart domContentLoadedEventEnd domComplete loadEventStart loadEventEnd".split(" "),Qa=ua("navigationStart"),gd=ua("domContentLoadedEventStart"),hd=
ua("loadEventStart"),$=Qa,$b="downlink downlinkMax effectiveType rtt saveData type".split(" "),ra,Db;ra=function(a,b,c){if(b&&"object"===typeof b){var d="id"in b&&b.id||da,g=c.title||null,f,e=Db(b,{params:c.required,fn:c.fn});if(e.missed.length)console.warn("[TopMailRu]"+(d?"["+d+"]":"")+" Error#1.14","Unspecified "+(1<e.missed.length&&e.missed.slice(0,-1).join(", ")+" and "||"")+e.missed.slice(-1)+" in "+a);else{var k=Db(b,{params:c.optional,fn:c.fn});f=[].concat(e.values).concat(k.values);e=[].concat(e.missed).concat(k.missed);
c.value&&(b="value"in b&&b.value,!0!==c.value&&(b=b||c.value),b?f.push("value: "+b):e.push("value"));c=f.length?"{ "+f.join(", ")+" }":"";f=e.length?"("+(1<e.length?e.slice(0,-1).join(", ")+" and "+e.slice(-1)+" are":e.slice(-1)+" is")+" empty)":"";d?console.info("[TopMailRu]["+d+"]: "+(g||a)+" "+c+" "+f):console.warn("[TopMailRu] Error#1.15","Undefined counter ID of "+a+" "+c)}}else console.warn("[TopMailRu][]["+a+"] Error#1.13")};Db=function(a,b){var c=[],d=[],g,f,e;if(b.params)for(g in b.params)if(b.params.hasOwnProperty(g)&&
!1!==b.params[g])if(f=g in a&&a[g],!0!==b.params[g]&&(f=f||b.params[g]),f)try{e=b.fn?b.fn:null,c.push(g+': "'+(e?e(g,f):f)+'"')}catch(k){console.warn("[TopMailRu] Error#1.16",k)}else d&&d.push(g);return{values:c,missed:d}};var x={},Ta=null,Sa=null,wb=[];m.prototype.callbackOnReady=function(a){q&&ra("onReady",a,{title:"OnReady callback"});a&&"object"===typeof a&&"function"===typeof a.callback&&(a.callback.call(a.context||null),la&&wb.push(a))};m.prototype.pageView=function(a){ta(a);a:if(a&&"object"===
typeof a&&a.id){5>Ia.length&&!aa(a.id,Ia)&&(Ia.push(a.id),!1!==a.beat&&ab.push(a.id),F.push(a),Ea&&Pb(a));la&&(Wa[a.id]=ca(!0,{},a),Wa[a.id].bfCache=!0);"detectBlocker"in a&&!a.detectBlocker&&(qb=!0);var b="string"===typeof a.ecommerce,c=b&&-1!==a.ecommerce.search(/\S/);if(5>$a.length&&!aa(a.id,$a)&&(!0===a.ecommerce||b&&!c||b&&c||!1!==a.ecommerce&&!b&&(aa(a.id,dd)||!aa(a.id,ed)))){$a.push(a.id);if(b&&c){if(yb&&(zb(a.ecommerce),C!==a.ecommerce)){C=a.ecommerce;E&&(E=[0,0,C]);break a}C=a.ecommerce;
E&&(E=[0,0,C])}b=[a.id];if(yb)for(var c=0,d=Za.length;c<d;c++)Qb(b,Za[c])}a.timespent=S&&(a.timespent||aa(a.id,ad)&&!1!==a.timespent);S&&(a.timespent?y.enable(a.id):y.disable(a.id));Bb||(Bb=!0===a.geolocation||a.timespent&&!1!==a.geolocation)&&lc(Cb);lb&&!aa(a.id,Ya)&&(Ya.push(a.id),Ub([a.id]))}q&&ra("pageView",a,{title:"Page view",optional:{url:G.href}});W(a)&&(D(J(a,"/counter",!1,!0)),Ga=w())};m.prototype.reachGoal=function(a){ta(a);q&&ra("reachGoal",a,{title:"Reach goal",value:!0,required:{goal:!0}});
if(W(a)&&"goal"in a&&a.goal){var b="value"in a&&a.value?parseInt(a.value)||"":"";D(J(a,K,!1,!0)+(";e="+escape("RG:"+b+"/"+a.goal)))}};var sb="VALUE";m.prototype.itemView=function(a){q&&ra("itemView",a,{title:"Item view",optional:{list:!0,pagetype:!0,productid:!0,totalvalue:!0},fn:function(a,b){return(""+b).replace(/;/g," ")}});if(W(a)){var b=a.list||"",c=a.productid||"",d=a.pagetype||"",f=a.totalvalue||0,h=Vc(a.id,d,f,c);h&&this.reachGoal(h);(new Image).src="https://ad.mail.ru/retarget/?counter="+
(a.id||da)+"&list="+b+"&productid="+c+"&pagetype="+d+"&totalvalue="+f+"&_="+Math.random();b="IV:"+f+"/"+(""+b).replace(/;/g," ")+";"+(""+c).replace(/;/g," ")+";"+(""+d).replace(/;/g," ");D(J(a,K,!1,!0)+(";e="+escape(b)))}};var Wc="vk_ecom_";m.prototype.sendEvent=function(a){ta(a);q&&ra("sendEvent",a,{title:"Send event",value:!0,required:{category:!0,action:!0},optional:{label:!0},fn:function(a,b){return(""+b).substring(0,300).replace(/;/g," ")}});if(W(a)&&"category"in a&&a.category&&"action"in a&&
a.action){var b=(""+a.category).substring(0,300),c=(""+a.action).substring(0,300),d="label"in a&&a.label?(""+a.label).substring(0,300):"",b="CE:"+("value"in a&&a.value?parseInt(a.value)||"":"")+"/"+(""+b).replace(/;/g," ")+";"+(""+c).replace(/;/g," ")+";"+(""+d).replace(/;/g," ");D(J(a,K,!1,!0)+(";e="+escape(b)))}};m.prototype.setUserID=function(a){if(null===a||!1===a||void 0===a)this.deleteUserID();else{var b=typeof a;"number"!==b&&"string"!==b?q&&console.warn("[TopMailRu] Error#1.17","Invalid user ID in setUserID"):
(R=a,q&&console.info("[TopMailRu]: Global user ID = "+R))}};m.prototype.getUserID=function(){return R||0===R?R:void 0};m.prototype.deleteUserID=function(){R=null;q&&console.info("[TopMailRu]: Reset global user ID to null")};m.prototype.setUserParams=function(a){if(null===a||!1===a||void 0===a)this.deleteUserParams();else if(O(a)){try{X=ca(!0,{},a)}catch(b){q&&console.warn("[TopMailRu] Error#1.22","Invalid user params in setUserParams");return}q&&console.info("[TopMailRu]: Global user params = "+xa(X))}else q&&
console.warn("[TopMailRu] Error#1.21","Invalid user params in setUserParams")};m.prototype.getUserParams=function(){var a=X?X:void 0;return a?ca(!0,{},a):void 0};m.prototype.deleteUserParams=function(){X=null;q&&console.info("[TopMailRu]: Reset global user params to null")};m.prototype.getClientID=function(){var a=ma;return a||0===a?a:void 0};m.prototype._MT_event=function(a,b,c){ta(a);q&&ra(b,a,{title:c});W(a)&&D(J(a,K,!1,!0)+(";e="+escape("MT:/"+b)))};m.prototype.miniAppEvent=function(a){this._MT_event(a,
"miniAppEvent","VK Mini App Event")};var Eb=function(a,b){if(S){var c=y.defaultID();W(a,c)&&(!O(a)||!("activity"in a&&a.activity)?q&&console.warn("[TopMailRu] Error#1.27","Invalid startActivity command: ID of activity is required"):y.startActivity(a.id||c,""+a.activity,null===b?!!a.canUseInBackground:b))}};m.prototype.startTimespent=function(a){Eb(a,null)};m.prototype.startForegroundTimespent=function(a){Eb(a,!1)};m.prototype.startAnytimeTimespent=function(a){Eb(a,!0)};m.prototype.updateTimespent=
function(a){if(S){var b=y.defaultID();W(a,b)&&(!O(a)||!("activity"in a&&a.activity)?y.updateActivity():"number"===typeof a.activity||"string"===typeof a.activity?y.updateActivity(a.id||b,""+a.activity):q&&console.warn("[TopMailRu] Error#1.28","Invalid updateActivity command: ID of activity should be number or string"))}};m.prototype.stopTimespent=function(a){if(S){var b=y.defaultID();W(a,b)&&(!O(a)||!("activity"in a&&a.activity)?y.stopActivity(!1):"number"===typeof a.activity||"string"===typeof a.activity?
y.stopActivity(a.id||b,""+a.activity,!1):q&&console.warn("[TopMailRu] Error#1.29","Invalid stopActivity command: ID of activity should be number or string"))}};m.prototype.incrementEventTimespent=function(a){if(S){var b=y.defaultID();W(a,b)&&(!a||!("activity"in a&&a.activity)?q&&console.warn("[TopMailRu] Error#1.31","Invalid incrementEventTimespent command: ID of countable activity is required"):y.incCount(a.id||b,""+a.activity))}};m.prototype.processEvent=function(a,b){if(a&&"object"===typeof a)if("type"in
a){if("onready"===a.type){if(b&&0>b)return;this.callbackOnReady(a)}else if(b&&0<b)return;switch(a.type){case "pageView":this.pageView(a);break;case "reachGoal":this.reachGoal(a);break;case "itemView":this.itemView(a);break;case "sendEvent":this.sendEvent(a);break;case "setUserID":"userid"in a&&this.setUserID(a.userid);break;case "deleteUserID":this.deleteUserID();break;case "setUserParams":"params"in a&&this.setUserParams(a.params);break;case "deleteUserParams":this.deleteUserParams();break;case "miniAppEvent":this.miniAppEvent(a);
break;case "startTimespent":this.startTimespent(a);break;case "startForegroundTimespent":this.startForegroundTimespent(a);break;case "startAnytimeTimespent":this.startAnytimeTimespent(a);break;case "updateTimespent":this.updateTimespent(a);break;case "stopTimespent":this.stopTimespent(a);break;case "incrementEventTimespent":this.incrementEventTimespent(a)}}else q&&console.warn("[TopMailRu] Error#1.19","Unspecified type of push event");else q&&console.warn("[TopMailRu] Error#1.18","Invalid push event")};
m.prototype.push=function(a){for(var b=0,c=arguments.length;b<c;b++)this.processEvent(arguments[b])};var pc=!1;m.prototype.onready=function(){pc||(pc=!0,!qb&&!Ea&&cd(Oc,Pc),zb(C),Qc())};var vb=!1;m.prototype.onload=function(){if(!vb){vb=!0;Fa=w();if(!Ja&&0<F.length){for(var a=";e="+escape("RT/load")+";et="+Fa,b=0;b<F.length;b++)D(J(F[b],K,!0,!0)+a);Ga=Fa}Sc()}};m.prototype.beat=function(){var a;if(!rb&&Va){var b=w();if(!(12E4<b-Va)){if(12E4<b-Ga){a=";e="+escape("RT/resend")+";et="+Fa;for(var c=0;c<
F.length;c++)!1!==F[c].beat&&D(J(F[c],K,!1,!0)+a)}else 0<ab.length&&(a=";e="+escape("RT/beat")+";ids="+escape(ab.join()),D(J({id:ab[0]},K,!1,!0)+a));Ga=b}}};var ub=!1;m.prototype.unload=function(){if(!ub){ub=!0;if(!Ja){var a;a=(a=Vb())?w()-a:void 0;a=";e="+escape("RT/unload")+";et="+w()+(a?";pvt="+escape(a):"");if(na.support){var b=na.getLog();a+=";vtauto="+b.auto}for(b=0;b<F.length;b++)D(J(F[b],K,!0,!0)+a)}la&&(x.dcl3&&(clearTimeout(x.dcl3),delete x.dcl3),x.pvt2&&(clearTimeout(x.pvt2),delete x.pvt2),
x.pvt15&&(clearTimeout(x.pvt15),delete x.pvt15),x.beat&&(clearInterval(x.beat),delete x.beat))}};m.prototype.activity=function(a){Va=w()};var ha=_tmr;_tmr=new m;S&&y.init();for(var v=0,Ma=ha.length,sa;v<Ma;v++)(sa=ha[v])&&"object"===typeof sa&&ta(sa);bb=(new Date).getTime();v=0;for(Ma=ha.length;v<Ma;v++)sa=ha[v],_tmr.processEvent(sa,1);Na=(new Date).getTime();v=0;for(Ma=ha.length;v<Ma;v++)sa=ha[v],_tmr.processEvent(sa,-1);"complete"===l.readyState||"loading"!==l.readyState&&!l.documentElement.doScroll?
(Sa=gd,_tmr.onready(),fc()):l.addEventListener?n(l,"DOMContentLoaded",Ua):l.attachEvent&&n(l,"readystatechange",Ua);"complete"===l.readyState?(Ta=hd,_tmr.onload()):la?n(f,"pageshow",tb):n(f,"load",tb);la?n(f,"pagehide",Ha):(n(f,"unload",Ha),n(f,"beforeunload",Ha));ec();if(!rb)try{for(var qc="scroll gesturechange touchmove mousedown mousemove mouseup touch".split(" "),id=function(a){n(l,a,function(){_tmr.activity(a)})},v=0;v<qc.length;v++)id(qc[v]);n(f,"scroll",function(){_tmr.activity("scallback")})}catch(jd){q&&
console.warn("[TopMailRu] Error#1.20",jd)}Oa=(new Date).getTime()}})();
