# Generated by Django 5.0.6 on 2024-06-12 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('width', models.IntegerField(verbose_name='Ширина')),
                ('thickness', models.FloatField(verbose_name='Толщина')),
                ('safe_layer', models.FloatField(verbose_name='Толщина защитного слоя')),
                ('fire_safety', models.CharField(max_length=5, verbose_name='Класс пожарной безопасности')),
                ('brand', models.CharField(max_length=20, verbose_name='Бренд')),
                ('link', models.CharField(max_length=200, verbose_name='Ссылка')),
                ('photo', models.CharField(max_length=250, verbose_name='Ссылка')),
            ],
        ),
    ]
