# Generated by Django 5.0.6 on 2024-06-12 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, max_length=20, verbose_name='Бренд'),
        ),
        migrations.AlterField(
            model_name='product',
            name='fire_safety',
            field=models.CharField(blank=True, max_length=5, verbose_name='Класс пожарной безопасности'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.CharField(max_length=250, verbose_name='Фото'),
        ),
    ]
