# Generated by Django 5.0.6 on 2024-06-13 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_product_options_alter_product_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unique_name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Уникальное имя'),
        ),
    ]
